mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trends/', include('trends.urls')),
]

trends/urls.py
from django.urls import path
from . import views

app_name= 'trends'
urlpatterns = [
    path('keyword/', views.keyword, name = 'keyword'),
    path('keyword/<int:pk>/', views.keyword_detail, name = 'keyword_detail'),
    path('crawling/', views.crawling, name = 'crawling'),
    path('crawling/histogram/', views.crawling_histogram, name = 'crawling_histogram'),
    path('crawling/advanced/', views.crawling_advanced, name = 'crawling_advanced'),
]

trends/models.py
from django.db import models

# Create your models here.
class Keyword(models.Model):
    name = models.CharField(max_length=20)
    created_at = models.DateField(auto_now_add=True)

class Trend(models.Model):
    name = models.TextField()
    result = models.IntegerField()
    search_period = models.TextField()
    created_at = models.DateField(auto_now_add=True)

    # keyword 1 : trends N, trend N 쪽에 ForeignKey 만들기

trends/forms.py
from django import forms
from .models import Keyword, Trend

class KeywordForm(forms.ModelForm):
    name = forms.CharField(label="키워드")
    class Meta:
        model = Keyword
        fields = ('name',)


class TrendForm(forms.ModelForm):

    class Meta:
        model = Trend
        fields = '__all__'

trends/views.py
from django.shortcuts import render, redirect
from .models import Keyword, Trend
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from .forms import KeywordForm, TrendForm
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from io import BytesIO
import base64

# Create your views here.
def keyword(request):
    keywords = Keyword.objects.all()
    if request.method == "POST":
        form = KeywordForm(request.POST)
        if form.is_valid():
            keyword = form.save()
            return redirect('trends:keyword')
    else:
        form = KeywordForm()
    context = {
        'form' : form,
        'keywords' : keywords
    }
    return render(request, 'trends/keyword.html', context)

def keyword_detail(request, pk):
    keyword = Keyword.objects.get(pk=pk)
    keyword.delete()
    return redirect('trends:keyword')

def crawling(request):
    # 저장했던 keyword를 불러온다
    keywords = Keyword.objects.all()
    # 크롤링
    for k in keywords:
        url = f'https://www.google.com/search?q={k.name}'
        driver = webdriver.Chrome()
        driver.get(url)
        
        html = driver.page_source
        soup = BeautifulSoup(html, 'html.parser')

        result_stats = soup.select_one("#result-stats")
        context = {
            'result' : result_stats.text,
        }
        # print(result_stats.text)
        t = result_stats.text
        t = t.replace(',','').strip()
        s = ''
        for i in range(len(t)):
            if t[i].isdigit()==True:
                s += t[i]
            elif t[i] == '개':
                break
        s = int(s)
        print(k.name)
        if Trend.objects.filter(name=k.name, search_period="all").exists():
            trend = Trend.objects.get(name=k.name, search_period="all")
            trend.result = s
            trend.save()
        else: 
            Trend.objects.create(name=k.name, result=s, search_period="all")
    return render(request, 'trends/crawling.html', context)

def crawling_histogram(request):
    # 크롤링 수행 후 수행 결과 막대 그래프 생성

    trends = Trend.objects.all()
    x = []
    y = []
    for trend in trends:
        x.append(trend.name)
        y.append(trend.result)

    plt.bar(x, y)
    plt.title('Technology Trend Analysis')
    plt.xlabel('Keyword')
    plt.ylabel('Result')
    
    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    img_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8').replace('\n', '')
    buffer.close()
    context = {
        'image' : f'data:image/png;base64, {img_base64}',
    }
    return render(request, 'trends/crawling_histogram.html', context)

def crawling_advanced(request):
    # 지난 1년 기준으로 크롤링 수행 후 막대 그래프 생성
    return render(request, 'trends/crawling_advanced.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Crawling</title>
</head>
<body>
  <h1>트렌드 분석 애플리케이션</h1>
  <a href=" {% url "trends:keyword" %}">키워드 추가</a>
  &verbar;
  <a href=" {% url "trends:crawling" %}">크롤링</a>
  &verbar;
  <a href=" {% url "trends:crawling_histogram" %}">히스토그램</a>
  &verbar;
  <a href=" {% url "trends:crawling_advanced" %}">지난 1년 크롤링</a>
  {% block content %}
  {% endblock content %}
  
</body>
</html>

trends/templates/trends/crawling.html
{% extends "base.html" %}

{% block content %}
<h3>크롤링 기초 - 전체 기간 검색 결과</h3>
<form action=" {% url "trends:crawling" %}" method="POST">
  {% csrf_token %}
  <p>{{ result }}</p>
  <hr>
</form>
{% endblock content %}

trends/templates/trends/crawling_advanced.html
{% extends "base.html" %}

{% block content %}

{% endblock content %}

trends/templates/trends/crawling_histogram.html
{% extends "base.html" %}

{% block content %}
<h1>전체 기간 검색 결과 히스토그램</h1>
  <img src="{{image}}" alt="">
{% endblock content %}

trends/templates/trends/keyword.html
{% extends "base.html" %}

{% block content %}
<h3>키워드 추가</h3>
<form method="POST">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="생성하기">
</form>
<hr>
<h4>분석을 원하는 키워드 목록</h4>
{% for keyword in keywords %}
  <form action=" {% url "trends:keyword_detail" keyword.pk %}" method="POST">
    {% csrf_token %}
    <p>{{ keyword.pk }}번째 키워드 - {{ keyword.name }}</p>
    <input type="submit" value="삭제하기">
  </form>
  <hr>
{% endfor %}
{% endblock content %}